app/context_construction/query_rewriter.py
app/model_inference/loaders/HyperCLOVA_loader.py

1. fortune 응답 구조를 overall만 보내는 형태로 단순화했습니다.
<br />
`/api/llm/fortune` 응답 구조가 바뀌었으니 풀스택에서도 message/data 구조에 맞춰 파싱하는지 확인해주세요.
<br />
- close #5

feat: 응답 구조 간소화로 fortune API 속도 및 안정성 개선

---

.github/workflows/cicd-dev.yml
.github/workflows/cicd-prod.yml
.github/workflows/cicd.yml
app/model_inference/loaders/HyperCLOVA_loader.py
app/model_inference/loaders/fortune_gemma_loader.py

1. 운세 기능 속도 최적화를 위한 모델 하이퍼클로바로 변경
2. torch.no_grad() → torch.inference_mode()로 변경
<br />
1. 현재 mps 에서는 7-10초
3. L4 최적화 적용한 환경에서 0.7-1.2초 예상
<br />
- close #15

15 feat 속도최적화

---

.github/workflows/cicd-cpu-prod.yml

feat: [cpu]환경변수누락

---

.gitignore
app/context_construction/prompts/fortune_prompt.py
app/fast_api/endpoints/fortune_router.py
app/fast_api/schemas/fortune_schema.py
app/model_inference/fortune_inference_runner.py
requirements.cpu.txt

1. 운세 생성시 name(실명)으로 받았던 필드를 nickname(영어이름)으로 수정했습니다.
<br />
🖐️To reviewers
- close #71

[feat] 운세 name -> nickname 필드 변경

---

.github/workflows/cicd-cpu-dev.yml
app/fast_api/endpoints/comment_router.py
requirements.cpu.txt

1. dev, prod서버 나눔
2. 요청 무한 반복 수정
3. Docker 버전 에러 수정

feat: [cpu]version error 수정

---

app/fast_api/endpoints/comment_router.py

1. 큐 재시도 없앰 -> 무한로딩 없앰
```
gcloud tasks queues update comment-queue \
--project=ktb8team-458916 \
--location=asia-southeast1 \
--max-attempts=1 \
--min-backoff=0s \
--max-backoff=0s \
--max-doublings=0
Updated queue [asia-southeast1/comment-queue].
```

feat: [cpu] 클라우드 큐 재시도 없앰

---

app/services/comment_service.py

1. Google cloud의 600초 이상 응답없음 문제 대응 목적

fix: [cpu] ReduceRetry

---

app/fast_api/endpoints/comment_router.py
app/services/comment_service.py

fix: [cpu]KoEnName

---

app/services/comment_service.py

refactoring: [cpu]summary

---

app/services/comment_service.py

fix: [cpu]arguments

---

app/services/comment_service.py

fix: [cpu]google500sec

---

Dockerfile.crawling

1. 벡터디비 변경에 따른 환경변수 수정하여 dockerfile 변경 완료
- close #120

chore: 크롤링용 Dockerfile에 Qdrant 및 GitHub 토큰 환경 변수 추가

---

.github/workflows/cicd-prod.yml

test: [gpu] 테스트

---

app/model_inference/rag_chat_runner.py

안녕, 바보야 와 같은 무관한 질문에 필터링 기준을 강화하여 FILTERED_RESPONSE가 출력되도록 변경하였습니다.

fix: adjusted_score 기준 상향하여 무관한 질문 필터링 개선

---

app/main_gpu.py
requirements.gpu.txt

1. `torch` 버전 `2.7.1`로 업그레이드
2. `torch.load()` 사용 시 발생하는 보안 오류(CVE-2025-32434) 해결
3. 불필요한 `warnings.filterwarnings("ignore", message="TypedStorage")` 코드 제거
<br />
1. 기존에 발생하던 `torch.load()` 관련 ValueError는 `torch>=2.6` 이상에서 해결됩니다
2. PyTorch 업그레이드 후 기존 suppress 코드(`warnings.filterwarnings(...)`)도 더 이상 필요하지 않아 제거했습니다

Feat/131 응답 개선

---

app/context_construction/prompts/badge_prompt.py

1. 보안 설정으로 봇으로 감지되어 크롤링이 막히는 경우가 발생하여 해당 경우에는 fallback로직을 세워 임의의 로고를 가져가도록 수정하였습니다.
2. logging추가.

[feat] 보안에 의한 크롤링 불가팀 로직추가

---

Dockerfile.badge
app/context_construction/prompts/badge_prompt.py
app/model_inference/badge_inference_runner.py
app/model_inference/loaders/badge_loader.py
requirements.badge.txt

1. 각 팀 로고 크롤링시, 업스케일링을 진행하여 해상도를 높임.
Original | Before | After
-- | -- | --
<br />
1. 업스케일링 경량 모델을 추가하여 각 팀 뱃지의 해상도를 높였습니다.
2. 메모리 최적화 로직을 추가하여, RAM 15GB -> 14GB로 불필요한 메모리를 삭제하였습니다.

[feat] 업스케일링 로직 추가

---

app/services/team_chat_service.py

1. AWQ 양자화한 모델로 변경합니다.
<br />
현재 vLLM을 이용한 LLM 추론 환경에서 GPU 메모리 부족(OOM) 문제가 발생하고 있습니다. 이를 해결하고 GPU 리소스 효율성을 극대화하기 위해, vLLM이 로드하는 LLM 모델에 양자화(Quantization)를 적용하여 GPU 메모리 사용량을 줄이고자 합니다.
AWQ 방식 채택
•	vLLM에서 공식적으로 지원하는 양자화 방식이므로, 안정적으로 사용할 수 있습니다.
•	모델 weight 자체를 4bit로 양자화하므로, GPU 메모리 사용량을 크게 줄일 수 있습니다.
•	bitsandbytes와 달리 실제 저장 파일도 가벼워지며, 배포 및 업로드에도 유리합니다.
•	추론 속도 저하 없이 양자화 효과를 얻을 수 있어, 실시간 응답이 중요한 서비스에 적합합니다.
•	LLaMA뿐만 아니라 대부분의 GPT-style 모델에 적용 가능하므로, HyperCLOVAX 모델에도 활용할 수 있습니다.
•	vLLM 명령어에서 --quantization awq 한 줄로 적용 가능하므로, 배포 과정이 간단합니다.
양자화 전(sunnyanna/hyperclovax-sft-1.5b-v4) | 양자화 후(sunnyanna/hyperclovax-sft-1.5b-v4-awq)
-- | --
항목 | 적용 전 | 적용 후
-- | -- | --
First token delay | 1.730초 | 1.389초
Full generation time | 1.814초 | 1.550초
AWQ 양자화 적용으로 인해,
- 첫 토큰 응답 시간은 약 20% 감소
- 전체 생성 시간은 약 15% …

refactor: 양자화 모델(v4-awq)로 변경 [gpu]

---

app/test/deploy.py

1. 클라우드 태그 관련 문제 해결 중 발생한 revert로 인한 pr입니다.

fix: revert문제해결

---

.github/workflows/cicd-badge-dev.yml
app/model_inference/badge_inference_runner.py

1. Canny이미지를 저장 후 불러오는 로직이 있는데, 해당 로직의 삭제가 필요함.
- 이슈: 원본이미지의 color를 추출하지 못함.
<br />
1. Canny이미지의 GCS 저장 및 로드 로직을 삭제하였습니다.
2. dev PR 승인된 내용에 변동사항 없습니다.
<br />
- close #213

feat: [badge] NoCanny
